[project]
name = "my-data-bi-project-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "duckdb>=1.3.2",
    "pandas>=2.0.3",
    "plotly>=6.4.0",
    "streamlit>=1.40.1",
]
